version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://server:8080
      - NEXT_PUBLIC_REDIRECT_URL=http://localhost:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - Port=8080
      - DB_URL=mongodb://mongo:27017/url-shortener
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=your-secret-key
      - CLIENT_PROD_URL=http://localhost:3000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
